### ISSUE TITLE
Remove the LICENSE file from recipe/ once the PyPI source has that file

### ISSUE THREAD

**Issue by mrakitin** [conda-forge/hklpy-feedstock#1]
https://github.com/bluesky/hklpy/pull/180 is merged to address that issue on the package side. Should be available after v0.3.16.

**Comment by prjemian** [comment]
@mrakitin Is it time to proceed with this issue?

**Comment by prjemian** [comment]
@mrakitin Looked at [bluesky](https://github.com/conda-forge/bluesky-feedstock/blob/41856f192bdfbd9bb5a18cc5615aec7cd612a67d/recipe/meta.yaml#L53), [databroker](https://github.com/conda-forge/databroker-feedstock/blob/621817ed2ae7e5d7989910062b13fbfe02c096a0/recipe/meta.yaml#L76), and [ophyd](https://github.com/conda-forge/ophyd-feedstock/blob/b127c07c7238a1480c2969d5243efc056ad935c0/recipe/meta.yaml#L41) recipes for examples.  All have a `LICENSE` file in the feedstock which is referenced from the conda recipe.

How to do this?

**Comment by mrakitin** [comment]
I removed the license file from the feedstock via https://github.com/conda-forge/hklpy-feedstock/pull/2/commits/9ddd8ec1a2fff719e9c02d8bfb83bf0423c1da88 (#2). The `license_file: LICENSE` field is needed in the `meta.yaml` file to point to the right file in the source distribution (from PyPI in this case).

**Comment by mrakitin** [comment]
This was done long ago.
